# Generated by Django 4.1.2 on 2022-10-06 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customusermodel_is_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_revenue_generated", models.IntegerField(blank=True, default=0)),
                ("items_sold", models.SmallIntegerField(blank=True, default=0)),
                ("items_bought", models.SmallIntegerField(blank=True, default=0)),
                (
                    "days_in_row",
                    models.SmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="number of days user visited the site in a row",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
