# Generated by Django 4.1.2 on 2022-10-10 08:55

import django.db.models.deletion
from django.db import migrations, models


#! AT THIS MIGRATION project WAS ROLLED BACK TO 003
class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customerprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("T", "Trial"),
                            ("N", "Normal"),
                            ("S", "Super"),
                            ("P", "Premium"),
                            ("X", "Free"),
                        ],
                        default="X",
                        max_length=1,
                    ),
                ),
                ("trial_used", models.BooleanField(default=False)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="customerprofile",
            options={"verbose_name_plural": "Customer Profiles"},
        ),
        migrations.AlterModelOptions(
            name="customusermodel",
            options={"ordering": ["id"], "verbose_name_plural": "Custom Users"},
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="subscription",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="accounts.subscription",
            ),
        ),
    ]
