# Generated by Django 4.1.2 on 2022-10-10 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_subscription_alter_customerprofile_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customusermodel",
            name="subscription",
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
