from django.conf import settings
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse


@api_view(["GET"])
def api_root(request, format=None):
    # users-list url name generated by the simple router

    name_links_dictionary = {
        "users": reverse("accounts:users-list", request=request, format=format),
    }

    # DRF Spectacular overrides DRF's default solution. The main changing point is settings.REST_FRAMEWORK["DEFAULT_SCHEMA_CLASS"]
    # depends on the settings root url changes
    if settings.REST_FRAMEWORK.get("DEFAULT_SCHEMA_CLASS") == "drf_spectacular.openapi.AutoSchema":
        name_links_dictionary.update({"schema": reverse("swagger-ui", request=request, format=format)})
    else:
        name_links_dictionary.update({"schema": reverse("openapi-schema-drf", request=request, format=format)})

    return Response(name_links_dictionary)


from allauth.socialaccount.providers.facebook.views import FacebookOAuth2Adapter
from dj_rest_auth.registration.views import SocialLoginView


class FacebookLogin(SocialLoginView):
    adapter_class = FacebookOAuth2Adapter
