# Generated by Django 4.1.2 on 2022-10-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="product_categories",
            new_name="product_hierarchies",
        ),
    ]
