# Generated by Django 4.1.2 on 2022-10-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_product_categories_game_product_hierarchies"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="all_product_categories",
            field=models.ManyToManyField(
                blank=True, related_name="games", to="products.category"
            ),
        ),
    ]
