# Generated by Django 4.1.2 on 2022-10-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_game_all_product_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["base_hierarchy", "hierarchy_identifier"],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
