# Generated by Django 4.1.2 on 2022-10-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_item_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="attributes",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="products.itemattribute"
            ),
        ),
    ]
