# Generated by Django 4.1.2 on 2022-10-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_item_attributes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemattribute",
            old_name="attribute",
            new_name="attribute_name",
        ),
        migrations.AddField(
            model_name="itemattribute",
            name="attribute_value",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="itemattribute",
            name="attribute_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
