# Generated by Django 4.1.2 on 2022-10-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_rename_attribute_itemattribute_attribute_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="attributes",
        ),
        migrations.AddField(
            model_name="itemattribute",
            name="object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="products.item",
            ),
        ),
    ]
