# Generated by Django 4.1.2 on 2022-10-17 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_remove_item_attributes_itemattribute_object"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="game",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.game",
            ),
        ),
    ]
